### ISSUE TITLE
SPI Fitter fails with division by zero error

### ISSUE THREAD

**Issue by bennahugo** [ska-sa/codex-africanus#170]
* Codex Africanus version: africanus.__version__
'0.2.0'
* Python version: 3.6
* Operating System: kubuntu 18.04

### Description

Division by zero error during spi fit

### What I Did

```
 - 13:26:21 - ClassCasaImage     [0.2/0.2 1.2/1.3 1.2Gb]   ----> Save image data as FITS file /home/bhugo/workspace/output/deep2_beamtest.restored.fits
/home/bhugo/workspace/DDFacet/DDFacet/Imager/WSCMS/ClassModelMachineWSCMS.py:334: RuntimeWarning: invalid value encountered in log
  alphai = (np.log(Ihigh) - np.log(Ilow))/(np.log(self.GridFreqs[0]/self.RefFreq) - np.log(self.GridFreqs[-1]/self.RefFreq))
DDFacet has encountered an unexpected error. Dropping you into pdb for a post-mortem.
(This is because you're running with --Debug-Pdb set to 'always'.)
Traceback (most recent call last):
  File "/home/bhugo/workspace/DDFacet/DDFacet/Imager/WSCMS/ClassModelMachineWSCMS.py", line 373, in GiveSpectralIndexMap
    alphai=alphai).compute()
  File "/home/bhugo/workspace/venv/lib/python3.6/site-packages/dask/base.py", line 165, in compute
    (result,) = compute(self, traverse=False, **kwargs)
  File "/home/bhugo/workspace/venv/lib/python3.6/site-packages/dask/base.py", line 436, in compute
    results = schedule(dsk, keys, **kwargs)
  File "/home/bhugo/workspace/venv/lib/python3.6/site-packages/dask/threaded.py", line 81, in get
    **kwargs
  File "/home/bhugo/workspace/venv/lib/python3.6/site-packages/dask/local.py", line 486, in get_async
    raise_exception(exc, tb)
  File "/home/bhugo/workspace/venv/lib/python3.6/site-packages/dask/local.py", line 316, in reraise
    raise exc
  File "/home/bhugo/workspace/venv/lib/python3.6/site-packages/dask/local.py", line 222, in execute_task
    result = _execute_task(task, data)
  File "/home/bhugo/workspace/venv/lib/python3.6/site-packages/dask/core.py", line 119, in _execute_task
    return func(*args2)
  File "/home/bhugo/workspace/venv/lib/python3.6/site-packages/dask/optimization.py", line 982, in __call__
    return core.get(self.dsk, self.outkey, dict(zip(self.inkeys, args)))
  File "/home/bhugo/workspace/venv/lib/python3.6/site-packages/dask/core.py", line 149, in get
    result = _execute_task(task, cache)
  File "/home/bhugo/workspace/venv/lib/python3.6/site-packages/dask/core.py", line 119, in _execute_task
    return func(*args2)
  File "/home/bhugo/workspace/venv/lib/python3.6/site-packages/africanus/model/spi/dask.py", line 27, in _fit_spi_components_wrapper
    maxiter=maxiter)
  File "/home/bhugo/workspace/venv/lib/python3.6/site-packages/africanus/model/spi/component_spi.py", line 71, in fit_spi_components
    jac, ncomps, nfreqs, tol, maxiter)
ZeroDivisionError: division by zero

During handling of the above exception, another exception occurred:
```

**Comment by bennahugo** [comment]
This is running WSCMS in DDFacet under python 3 with the current ssd-py3 branch

**Comment by sjperkins** [comment]
Last line in the exception points to this call to the numba function

https://github.com/ska-sa/codex-africanus/blob/a2e69dc2cca3d93e0b1607414051cc8ff43943e9/africanus/model/spi/component_spi.py#L70-L71

There are two places where division occurs:

https://github.com/ska-sa/codex-africanus/blob/a2e69dc2cca3d93e0b1607414051cc8ff43943e9/africanus/model/spi/component_spi.py#L11-L15

and:

https://github.com/ska-sa/codex-africanus/blob/a2e69dc2cca3d93e0b1607414051cc8ff43943e9/africanus/model/spi/component_spi.py#L40-L42

@bennahugo Is it possible that the Reference Frequency (freq0) is zero? Otherwise the determinant might be problematic. What do you think @landmanbester

**Comment by bennahugo** [comment]
```
(Pdb) p self.RefFreq
1049833007.8125
(Pdb) p weights
array([1., 1.], dtype=float32)
(Pdb) I0i
array([ 6.8757708e-12, -7.1942825e-12, -9.1409953e-14, ...,
        1.6151452e-11, -9.0958473e-12, -6.1750076e-12], dtype=float32)
(Pdb) alphai=alphai
(Pdb) p alphai
array([ 1.8722017,        nan,        nan, ..., -5.8129096,        nan,
              nan], dtype=float32)
```
possibly not handling the nans correctly here

**Comment by landmanbester** [comment]
Hmmm looks like you might be trying to fit negative pixels or something. I0i and aplhai are initial guesses for the non-linear fit in log space. I did not check if they are valid initial guesses and in ths case it appears they are not. Ca yu see what happens if you leave them out completely? I.e. leave them out completely in [this](https://github.com/cyriltasse/DDFacet/blob/5dd0568842667e073601ce1c446f1ec62d9cc117/DDFacet/Imager/WSCMS/ClassModelMachineWSCMS.py#L370) call  so it should read

alpha, varalpha, Iref, varIref = fit_spi_components(FitCubeDask, weightsDask, freqsDask, self.RefFreq).compute()

**Comment by bennahugo** [comment]
The initial guesses are probably a noise issue. Is the sigma errors not specified as an initial weight like you would have for a curve fit? From watercooler discussion the general rule of thumb is not to try and fit slopes and curvature below 20-30 sigma. Here is a plot to show that for two fields we worked on recently:
![image](https://user-images.githubusercontent.com/7934586/72501214-f3f0e500-383e-11ea-95fc-908439a3b3cf.png)




It looks like it is running slightly further but crashes then with the following:
```
 - 08:58:11 - ClassCasaImage     [0.2/0.2 1.2/1.3 1.2Gb]   ----> Save image data as FITS file /home/bhugo/workspace/output/deep2_beamtest.app.restored.fits
DDFacet has encountered an unexpected error. Dropping you into pdb for a post-mortem.
(This is because you're running with --Debug-Pdb set to 'always'.)
Traceback (most recent call last):
  File "/home/bhugo/workspace/DDFacet/DDFacet/Imager/WSCMS/ClassModelMachineWSCMS.py", line 370, in GiveSpectralIndexMap
    alpha, varalpha, Iref, varIref = fit_spi_components(FitCubeDask, weightsDask, freqsDask, self.RefFreq).compute()
  File "/home/bhugo/workspace/venv/lib/python3.6/site-packages/dask/base.py", line 165, in compute
    (result,) = compute(self, traverse=False, **kwargs)
  File "/home/bhugo/workspace/venv/lib/python3.6/site-packages/dask/base.py", line 436, in compute
    results = schedule(dsk, keys, **kwargs)
  File "/home/bhugo/workspace/venv/lib/python3.6/site-packages/dask/threaded.py", line 81, in get
    **kwargs
  File "/home/bhugo/workspace/venv/lib/python3.6/site-packages/dask/local.py", line 486, in get_async
    raise_exception(exc, tb)
  File "/home/bhugo/workspace/venv/lib/python3.6/site-packages/dask/local.py", line 316, in reraise
    raise exc
  File "/home/bhugo/workspace/venv/lib/python3.6/site-packages/dask/local.py", line 222, in execute_task
    result = _execute_task(task, data)
  File "/home/bhugo/workspace/venv/lib/python3.6/site-packages/dask/core.py", line 119, in _execute_task
    return func(*args2)
  File "/home/bhugo/workspace/venv/lib/python3.6/site-packages/dask/optimization.py", line 982, in __call__
    return core.get(self.dsk, self.outkey, dict(zip(self.inkeys, args)))
  File "/home/bhugo/workspace/venv/lib/python3.6/site-packages/dask/core.py", line 149, in get
    result = _execute_task(task, cache)
  File "/home/bhugo/workspace/venv/lib/python3.6/site-packages/dask/core.py", line 119, in _execute_task
    return func(*args2)
  File "/home/bhugo/workspace/venv/lib/python3.6/site-packages/africanus/model/spi/dask.py", line 27, in _fit_spi_components_wrapper
    maxiter=maxiter)
  File "/home/bhugo/workspace/venv/lib/python3.6/site-packages/africanus/model/spi/component_spi.py", line 69, in fit_spi_components
    out[2, :] = data[:, ref_freq_idx]
ValueError: could not broadcast input array from shape (72,2) into shape (72)
```

**Comment by landmanbester** [comment]
This is just a usage error from within DDF. I recommend using the spectral index fitter in africanus [here](https://github.com/ska-sa/codex-africanus/tree/master/africanus/model/spi/examples) if you need to make spi maps. You can specify a multiple of the rms above which components should be fit (also in the DDF parset). Closing this and moving the ticket to DDF
