### ISSUE TITLE
simple_spi_fitter falling over on single-freq data

### ISSUE THREAD

**Issue by o-smirnov** [ska-sa/codex-africanus#175]
Just trying to convolve for now:
```
python ~/projects/codex-africanus/africanus/model/spi/examples/simple_spi_fitter.py --fitsmodel ../delay/A3556-delay3-noblcut-deeper-MFS-image.fits --fitsresidual ../delay/A3556-delay3-noblcut-deeper-MFS-model.fits --threshold 10 --beammodel ~/beams/meerkat_pb_jones_cube_95channels --ncpu 16  --beampars 0.003675 0.00289 85 --output bm


 
Input Options:
fitsmodel  =  ../delay/A3556-delay3-noblcut-deeper-MFS-image.fits
fitsresidual  =  ../delay/A3556-delay3-noblcut-deeper-MFS-model.fits
ms  =  None
field  =  0
outfile  =  None
beampars  =  [0.003675, 0.00289, 85.0]
threshold  =  10.0
maxDR  =  100
ncpu  =  16
beammodel  =  /home/oms/beams/meerkat_pb_jones_cube_95channels
output  =  bm
padding_frac  =  0.2
dont_convolve  =  False
circularise_beam  =  False
corr_type  =  linear
channel_weights  =  None
 
 
Using 16 threads
 
 
Using emaj = 3.67e-03, emin = 2.89e-03, PA = 8.50e+01 

Image shape =  (10000, 10000)
Cube frequencies:
[1.28e+09]
Reference frequency is 1.28e+09 Hz 

Computing clean beam
Doing FFT's
Wrote convolved model to ../delay/convolved_model.fits 

Interpolating beam
Loading fits beam patterns from /home/oms/beams/meerkat_pb_jones_cube_95channels
Supplied beam has shape  (257, 257, 95, 1, 1)
Traceback (most recent call last):
  File "/home/oms/projects/codex-africanus/africanus/model/spi/examples/simple_spi_fitter.py", line 688, in <module>
    main(args)
  File "/home/oms/projects/codex-africanus/africanus/model/spi/examples/simple_spi_fitter.py", line 535, in main
    beam_image = interpolate_beam(xx, yy, freqs, args)
  File "/home/oms/projects/codex-africanus/africanus/model/spi/examples/simple_spi_fitter.py", line 316, in interpolate_beam
    beam_source = np.transpose(beam_image, axes=(1, 0))
  File "<__array_function__ internals>", line 6, in transpose
  File "/home/oms/.venv/cc/lib/python3.6/site-packages/numpy/core/fromnumeric.py", line 651, in transpose
    return _wrapfunc(a, 'transpose', axes)
  File "/home/oms/.venv/cc/lib/python3.6/site-packages/numpy/core/fromnumeric.py", line 61, in _wrapfunc
    return bound(*args, **kwds)
ValueError: axes don't match array
```

**Comment by landmanbester** [comment]
@o-smirnov can you give that a go? Note I suspect there is something wrong with the error maps. I'll have a look later today if I get a chance

**Comment by landmanbester** [comment]
@o-smirnov was this fixed?

**Comment by o-smirnov** [comment]
You mean just convolving a single-frequency image? Yes, I got that to work. We'll need to retest it anyway once you've split things into standalone scripts...
