### ISSUE TITLE
wsclean source model parser can't handle nans 

### ISSUE THREAD

**Issue by sjperkins** [ska-sa/codex-africanus#249]
* Codex Africanus version: latest
* Python version: 3.6
* Operating System: Ubuntu 18.04

### Description

Python's literal_eval is used to parse wsclean source model field and this fails when nans are encountered:

https://bugs.python.org/issue15245

Related crystalball issue https://github.com/paoloserra/crystalball/issues/42

### What I Did

```
# running /home/oms/.venv/stimela/bin/crystalball --output-column DIR1_DATA --within dd.reg --num-sources 1000 --sky-model im4/im4-s08-sources.txt ../msdir/1608538564_sdp_l0-Jupiter-scan08.ms
# 2021-05-17 12:45:57 | INFO     | crystalball:_predict | Crystalball version 0.3.0
# 2021-05-17 12:45:57 | INFO     | region:load_regions | Read 1 inclusion region(s) from dd.reg
# Traceback (most recent call last):
#   File "/home/oms/.venv/stimela/bin/crystalball", line 33, in <module>
#     sys.exit(load_entry_point('crystalball', 'console_scripts', 'crystalball')())
#   File "/home/oms/projects/crystalball/crystalball/crystalball.py", line 155, in predict
#     return _predict(args)
#   File "/home/oms/projects/crystalball/crystalball/crystalball.py", line 172, in _predict
#     num=args.num_sources or None)
#   File "/home/oms/projects/crystalball/crystalball/wsclean.py", line 62, in import_from_wsclean
#     in load(wsclean_comp_list)}
#   File "/home/oms/.venv/stimela/lib/python3.6/site-packages/africanus/model/wsclean/file_model.py", line 208, in load
#     return _parse_lines(fh, line_nr, column_names, defaults, converters)
#   File "/home/oms/.venv/stimela/lib/python3.6/site-packages/africanus/model/wsclean/file_model.py", line 139, in _parse_lines
#     data_list.append(conv(value))
#   File "/usr/lib/python3.6/ast.py", line 85, in literal_eval
#     return _convert(node_or_string)
#   File "/usr/lib/python3.6/ast.py", line 61, in _convert
#     return list(map(_convert, node.elts))
#   File "/usr/lib/python3.6/ast.py", line 70, in _convert
#     operand = _convert(node.operand)
#   File "/usr/lib/python3.6/ast.py", line 84, in _convert
#     raise ValueError('malformed node or string: ' + repr(node))
# ValueError: malformed node or string: <_ast.Name object at 0x7fcd58f2e6a0>
```

Source model available at `/net/muddy/home/oms/projects/Jove/selfcal2/im4/im4-s08-sources.txt`

**Comment by KshitijT** [comment]
No one can handle nans, @sjperkins .
